POST http://localhost:3333/events
Content-Type: application/json

 {
  "title": "Eject Awards",
  "details": "Premiar todos os membros que contribuiram para algo esse ano",
  "maximumAttendees": 27
 }