POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/015fbfbf-2229-422d-bdcd-80fbcae5d503/attendee
Content-Type: application/json

{
  "name": "Fellipe M Dino",
  "email": "fellipemiguel@email.com"
}

###

GET http://localhost:3333/events/a9a0bbcc-a020-45e8-a376-942c1f61cc93

###

GET http://localhost:3333/attendees/2/badge